/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */
val javaparserVersion by extra { "3.24.4" }
val jmhVersion by extra { "1.35" }
val jUnitJupiterVersion by extra { "5.9.0" }
val jUnit4Version by extra { "4.13.2" }
val bcelVersion by extra { "6.5.0" }

subprojects {
    repositories {
        mavenCentral()
    }
}
