/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */
val javaparserVersion by extra { "3.15.3" }
val jmhVersion by extra { "1.22" }
val jUnitJupiterVersion by extra { "5.5.2" }
val jUnit4Version by extra { "4.12" }

subprojects {
    repositories {
        jcenter()
    }
}